feat: add highlight theme option
TypeStrong/typedoc pull request #1486
Opened 2021-01-26 23:18 UTC by refineddigital

adds support for changing the default code highlighter theme

2021-01-27 01:58 UTC, Gerrit0 requested changes
Looking good, just a couple comments :)

2021-01-27 01:58 UTC, Gerrit0 commented on src/lib/utils/highlighter.ts
> +        theme: theme || "light-plus",
I'd rather specify this as the default in the option declaration - then it can be picked up and shown in the typedoc.json schema file.

2021-01-27 01:58 UTC, Gerrit0 commented on src/lib/utils/options/sources/typedoc.ts
> +    });
Can you add a validation function to this to ensure that the user provided is valid? I believe Shiki exports an array of themes.

2021-01-27 20:47 UTC, refineddigital commented
@Gerrit0 ok, I think I have now done as you have requested.

2021-01-29 17:46 UTC, merged

2021-01-29 17:47 UTC, Gerrit0 commented
Looks great, thanks! Will be published either today or tomorrow :)

2021-01-31 19:04 UTC, refineddigital commented
You are a champion, thanks @Gerrit0