TypeDoc displays a superfluous type on number constants implementation
TypeStrong/typedoc pull request #2721
Opened 2024-09-29 19:49 UTC by Corso02

This PR is implementing the enhancement mentioned in #2717. 
When the type is exactly the same thing as the value, the type is not printed to docs.

2024-09-29 20:52 UTC, Gerrit0 requested changes

2024-09-29 20:52 UTC, Gerrit0 commented on src/lib/output/themes/default/partials/member.declaration.tsx
> +                // should be unreachable
This isn't true, `value = 0` is falsy, it could also be a literal `false`

2024-09-29 20:52 UTC, Gerrit0 commented on src/lib/output/themes/default/partials/member.declaration.tsx
> +    /** Fix for #2717. If type is the same as value the type is omited */
Typo, "omitted"

2024-09-29 20:52 UTC, Gerrit0 commented on src/lib/output/themes/default/partials/member.declaration.tsx
> +            let defaultValue = props.defaultValue!;
This assertion is unsafe, `defaultValue` may very well be undefined here, which would result in a crash due to using `defaultValue.toString()` below. Given that if it is `undefined` you want that comparison to be false anyways, I'd recommend just getting rid of the `toString` and the non-null assertion here.

2024-09-29 20:52 UTC, Gerrit0 commented on src/lib/output/themes/default/partials/member.declaration.tsx
> +            if (typeof value === "object") {
I don't think this is the logic we want. This is the case for bigint literals. TypeDoc splits them up as they can't be JSON serialized, but in this case we'd want to check that it is different.

2024-09-29 20:52 UTC, Gerrit0 commented on src/lib/output/themes/default/partials/member.declaration.tsx
> +            const typeObject = props.type.toObject();
I'd prefer to not call `toObject` here. That is intended for serialization, and this code ought to work with the non-serialized object instance. You might find `props.type.toString()` useful, however.

2024-09-29 20:52 UTC, Gerrit0 commented on src/lib/output/themes/default/partials/member.declaration.tsx
> +                // If the default value is string and it's wrapped in ' in the code, the value is wrapped in " and vice-versa
Ew... so this breaks if there are any escape sequences in the string... I'm okay ignoring that edge case for now.

2024-09-30 06:27 UTC, Corso02 commented
Hi @Gerrit0, thank you for your code review. I'll look into fixing the issues mentioned in the coming days. Would it be possible to assign me the #2717 issue? Thank you so much for your attention and participation.

2024-09-30 07:08 UTC, Corso02 commented
I managed to fix most of the issues, below I have some examples of what I looked into.

Code: ```const falseVal = false;```
Output:
![image](https://github.com/user-attachments/assets/05b7aed2-37b3-40e3-8b17-be52b9bb5917)

Code: ```const zero = 0;```
Output:
![image](https://github.com/user-attachments/assets/1ef2a0ed-9ec3-4787-845c-6f62e78a7c44)

Code: ```const escaped_str_end = "Testing with escaped at the end\n"```
Output:
![image](https://github.com/user-attachments/assets/8f76e0c4-22da-4847-9375-f0e46377f44b)
(This works the same with escaped character at the start or in the middle)


I have one question.
Consider this code:
```const bigNumber = 9007199254740991n;```
I get the output below:
![image](https://github.com/user-attachments/assets/9fa09128-58cb-48f3-aa79-b2f9b13425ba)

Is this the correct output? Or should it be different? Thanks in advance.

2024-10-03 14:43 UTC, Gerrit0 approved these changes

2024-10-03 14:44 UTC, merged